### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by chrisjurich** [JingyiChris/SHAPELoop#1]
Hi,
Thanks for making this work publicly available. I tried running the package with the following command from `SHAPELoop/`:
`$ bin/SHAPELoop -s example/test.seq -r example/test.shape -o test`

With this command I get the following error: 
```Traceback (most recent call last):
  File "/home/cjurich/projects/SHAPELoop/scripts/shapel.py", line 153, in <module>
    selected_id = select_can(score_for_can,can_score_tmp,e_dot,ctrl_score)
  File "/home/cjurich/projects/SHAPELoop/scripts/select_candidate.py", line 46, in select_can
    sel_id = get_selected_candidate(rna_score,poor_loop_score)
  File "/home/cjurich/projects/SHAPELoop/scripts/select_candidate.py", line 38, in get_selected_candidate
    if hscore >= poor_loop_score:
TypeError: '>=' not supported between instances of 'int' and 'dict_values'
```

I tried to take a look at this error but it seems to be somewhat deep in the algorithm so I didn't want to change it.

Thanks in advance

**Comment by JingyiChris** [comment]
Thank you for raising this issue. We have updated the code. Please try the new version.

**Comment by chrisjurich** [comment]
Thank you for the rapid response and fix. The test example now works for me!
